public class Assignment {
    public static void AverageMethodA() {

        Integer a = 3;
        Integer b = 4;
        Integer c = 5;

        Decimal av = (a+b+c)/3;

    }
    public static void AverageMethodB(Integer a, Integer b, Integer c){

        Decimal av = (a+b+c)/3;
    }
    public static Decimal AverageMethodC(){

        Integer a = 3;
        Integer b = 4;
        Integer c = 5;

        Decimal av = (a+b+c)/3;

        return av;
    }
    public static Decimal AverageMethodD(Integer a, Integer b, Integer c) {
    
      Decimal av = (a+b+c)/3;

      return av;
    }
    public void AverageMethodE(Integer a, Integer b, Integer c) {

        
      Decimal av = (a+b+c)/3;

    }
    public void AverageMethodF() {

        Integer a = 3;
        Integer b = 4;
        Integer c = 5;

        Decimal av = (a+b+c)/3;

    }
    public Decimal AverageMethodG() {

        Integer a = 3;
        Integer b = 4;
        Integer c = 5;

        Decimal av = (a+b+c)/3;
         return av;


    }
    public Decimal AverageMethodH(Integer a, Integer b, Integer c) {

     Decimal av = (a+b+c)/3;
     return av;

    }
    

}