public class Calculator {
    public static void  Addition(Integer a, Integer b) {
        
        Integer sum = a + b;

        system.debug('Sum of ' + a + ' and' + b + 'equals' + sum);

    }
    public static void  Addition(Integer a, Integer b, Integer c ) {
        
        Integer sum = a + b + c;

        system.debug('Sum of ' + a + ' and' + b + ' and' + c + ' equals' + sum);

       
    }
    public static void  Addition(Integer a, Decimal b) {
        
        Decimal sum = a * b;

        system.debug('Sum of ' + a + ' and' + b + 'equals' + sum);

    }
}