public class Cars {
    public string model;//variable
    public string color;//variable
    public Date manfDate;//variable
    public Boolean isClean;//variable
    public void display(){
        system.debug('Model of the car is ' +model);
        system.debug('Color of the car is ' +color);
        system.debug('Manufactured  of the car is ' +manfDate);
        system.debug('Is the car clean title '+isClean);
        
    }
}