public class DemoApex {
    public static void methodA() {
        Boolean isActive = true;
         System.debug('Value of isActive '+ isActive);

    }
    public static void methodB(){
        String fName= 'Meltem' ;
        String lName = 'Vurgun';
        System.debug('Name = ' + fName + ' ' + lName);
    }
    public static void methodC(){
        ID accId = '0018Z00002ue9RLQAY';
        System.debug('Id ' + accId);
    }
}